version: '3'
services:
  app:
    image: app
    build: ./blog
    ports:
      - 8080:8080
    environment:
      APP_DATABASE_HOST: db
      APP_DATABASE_USERNAME: pguser
      APP_DATABASE_PASSWORD: pgpass
  db:
    image: postgres:11.3
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
